-- Keluarga Ledger database setup.
-- Paste this whole file into Supabase → SQL Editor → New query → Run.
-- Safe to run again: every statement is idempotent.
--
-- Only the server (using the secret / service-role key) can read or write
-- anything here. Row-level security is on with no policies and the public
-- API roles have no grants, so the publishable/anon key can't see any data.

create sequence if not exists households_seq;

create table if not exists users (
  id bigint generated by default as identity primary key,
  household_id bigint not null,
  open_id text not null unique,
  name text,
  email text,
  login_method text,
  role text not null default 'user' check (role in ('user', 'admin')),
  pin_hash text,
  pin_fail_count integer not null default 0,
  pin_locked_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists subcon_jobs (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  work_date bigint not null,
  job_title text not null,
  client_name text,
  location text,
  income_cents bigint not null,
  expense_cents bigint not null default 0,
  cost_lines jsonb not null default '[]',
  invoice_attachment_ids jsonb not null default '[]',
  worker_payments jsonb not null default '[]',
  worker_payment_cents bigint not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists subcon_jobs_user_date_idx on subcon_jobs (user_id, work_date desc);

create table if not exists chili_customers (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  name text not null,
  phone text,
  location text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists chili_customers_user_idx on chili_customers (user_id);
-- Added after launch: how the customer usually pays.
alter table chili_customers add column if not exists payment_terms text not null default 'on_delivery'
  check (payment_terms in ('on_delivery', 'next_delivery'));

create table if not exists chili_sales (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  sale_date bigint not null,
  customer_id bigint,
  recipient_name text not null,
  customer_contact text,
  grade_lines jsonb not null default '[]',
  quantity_kg text not null,
  price_per_kg_cents bigint not null,
  total_cents bigint not null,
  delivery_notes text,
  attachment_ids jsonb not null default '[]',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists chili_sales_user_date_idx on chili_sales (user_id, sale_date desc);
-- Added after launch: Grade A / Grade B lines per sale.
alter table chili_sales add column if not exists grade_lines jsonb not null default '[]';
-- Added after launch: when the sale was paid (epoch ms); null = still owed. Sales that
-- existed before this column count as paid — backfilled only when the column is created,
-- so re-running this file never marks unpaid sales as paid.
do $$ begin
  if not exists (select 1 from information_schema.columns
                 where table_schema = 'public' and table_name = 'chili_sales' and column_name = 'paid_at') then
    alter table chili_sales add column paid_at bigint;
    update chili_sales set paid_at = sale_date;
  end if;
end $$;

create table if not exists chili_expenses (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  expense_date bigint not null,
  category text not null,
  amount_cents bigint not null,
  notes text,
  attachment_ids jsonb not null default '[]',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists chili_expenses_user_date_idx on chili_expenses (user_id, expense_date desc);

create table if not exists staff (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  name text not null,
  ic_number text,
  bank_account_number text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists staff_user_idx on staff (user_id);

-- Metadata for receipt/invoice files; the bytes live in the "attachments"
-- storage bucket at the path in file_id / thumb_file_id.
create table if not exists attachments (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  uploaded_by_user_id bigint not null,
  kind text not null check (kind in ('invoice', 'receipt')),
  file_name text not null,
  mime_type text not null,
  size_bytes integer not null,
  width integer,
  height integer,
  file_id text not null,
  thumb_file_id text,
  linked_type text,
  linked_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists attachments_link_idx on attachments (user_id, linked_type, linked_id);
create index if not exists attachments_orphan_idx on attachments (linked_type, created_at);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('attachments', 'attachments', false, 5000000, array['image/jpeg', 'application/pdf'])
on conflict (id) do nothing;

-- Atomic helpers the server calls via RPC.

create or replace function allocate_household_id()
returns bigint
language sql
as $$ select nextval('households_seq') $$;

-- Counts a failed PIN attempt; returns attempts left (0 = now locked).
create or replace function record_pin_failure(p_user_id bigint, p_max_attempts int, p_lock_seconds int)
returns int
language plpgsql
as $$
declare
  attempts int;
begin
  update users set pin_fail_count = pin_fail_count + 1 where id = p_user_id returning pin_fail_count into attempts;
  if attempts is null then
    return p_max_attempts - 1;
  end if;
  if attempts >= p_max_attempts then
    update users set pin_fail_count = 0, pin_locked_until = now() + make_interval(secs => p_lock_seconds) where id = p_user_id;
    return 0;
  end if;
  return p_max_attempts - attempts;
end;
$$;

create or replace function storage_usage()
returns table (file_count bigint, attachment_bytes bigint, storage_bytes bigint)
language sql
security definer
set search_path = ''
as $$
  select
    (select count(*) from public.attachments),
    (select coalesce(sum(size_bytes), 0) from public.attachments)::bigint,
    (select coalesce(sum((metadata ->> 'size')::bigint), 0) from storage.objects where bucket_id = 'attachments')::bigint
$$;

-- Lock everything down to the server's secret key.

alter table users enable row level security;
alter table subcon_jobs enable row level security;
alter table chili_customers enable row level security;
alter table chili_sales enable row level security;
alter table chili_expenses enable row level security;
alter table staff enable row level security;
alter table attachments enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
revoke all on function allocate_household_id() from public, anon, authenticated;
revoke all on function record_pin_failure(bigint, int, int) from public, anon, authenticated;
revoke all on function storage_usage() from public, anon, authenticated;
grant usage on sequence households_seq to service_role;
grant execute on function allocate_household_id() to service_role;
grant execute on function record_pin_failure(bigint, int, int) to service_role;
grant execute on function storage_usage() to service_role;

notify pgrst, 'reload schema';
